add_subdirectory(world)
add_subdirectory(ecs-comp)
add_subdirectory(ecs)
add_subdirectory(game-objects)
add_subdirectory(obj-builder)
add_subdirectory(ai)
add_subdirectory(mod)
add_subdirectory(modding)
add_subdirectory(server)
add_subdirectory(client)
add_subdirectory(obj-pool)
add_subdirectory(opool-client)
